backend:
  name: github
  repo: ehowey/gatsby-starter-catalyst-writer
media_folder: static/assets/images
public_folder: assets
collections:
  - label: Published Work
    name: published
    widget: list
    file: data/test.yml
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publication, name: publication, widget: string }
      - { label: Published Date, name: date, widget: date }
      - { Label: URL, name: url, widget: string }
