backend:
  name: github
  repo: ehowey/gatsby-starter-catalyst-writer
media_folder: static/assets/images
public_folder: assets
collections:
  - name: "publishedwork"
    label: "Published Work"
    description: "List of all published work"
    files:
      - label: "List of Published Work"
        name: "work"
        file: "data/test.yml"
        fields:
          - label: "Published Work List"
            name: "workList"
            widget: "list"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Publication, name: publication, widget: string }
              - { label: Published Date, name: date, widget: date }
              - { Label: URL, name: url, widget: string }
